### ISSUE TITLE
System.InvalidCastException from 'Fonet.Layout.BlockArea' to 'Fonet.Layout.AreaContainer'

### ISSUE THREAD

**Issue by xavier-atero** [cajuncoding/PdfTemplating.XslFO#3] opened 2020-04-29 12:49 UTC
I have tested the **XslFO.ViewerApplication** with the Apache FOP Examples [https://xmlgraphics.apache.org/fop/examples.html](https://xmlgraphics.apache.org/fop/examples.html) and some of them throw a **System.InvalidCastException**

**STR**
1- Run XslFO.ViewerApplication
2- Load Xsl-FO Source file: fop-2.3\examples\fo\basic\images.fo

**Expected result**
The pdf file is generated

**Actual result**
```
[XslFORenderer] System.InvalidCastException: No se puede convertir un objeto de tipo 'Fonet.Layout.BlockArea' al tipo 'Fonet.Layout.AreaContainer'.
   en Fonet.Fo.Flow.BlockContainer.Layout(Area area)
   en Fonet.Fo.Flow.Block.Layout(Area area)
   en Fonet.Fo.Flow.Flow.Layout(Area area, Region region)
   en Fonet.Fo.Flow.Flow.Layout(Area area)
   en Fonet.Fo.Pagination.PageSequence.Format(AreaTree areaTree)
   en Fonet.StreamRenderer.Render(PageSequence pageSequence)
   en Fonet.Fo.FOTreeBuilder.EndElement()
   en Fonet.Fo.FOTreeBuilder.Parse(XmlReader reader)

```
**Notes**
Removing the fo:block-container element from the .fo file renders the pdf file as expected:
```
<fo:block-container width="40mm" background-color="lightgray">
   <fo:block><fo:external-graphic src="../graphics/asf-logo-nt.png" width="100%" content-width="scale-to-fit" content-height="100%" border="solid 0.1pt" background-color="yellow"/> 
   </fo:block>
</fo:block-container>
```
By the way, nice development!

**Comment by cajuncoding** [comment] 2020-05-08 06:55
Thanks! I hope you are finding something useful/helpful from the project.

Unfortunately the version of FONet incorporated into the project is old (no updates in many years) and hasn’t been updated nearly as much as the Apache FOP project, so it’s not surprising that the samples may use features simply not supported.

I believe this is described in the project read me markdown...

I did not author the original FONet port so I’m not versed well enough I raw Pdf generation to effectively debug or resolve issues in the underlying FONet code.

I truly wish we had a more updated external .Net project that could be referenced/leveraged instead of the embedded version I currently have.

**Comment by cajuncoding** [comment] 2020-07-18 06:57
FYI, @xavier-atero in case it's helpful for now or in the future....

I'm actively working on my new repo for serverless implementation of Apache FOP via Azure Functions -- providing a microservice for rendering Xsl-FO with all the latest features of ApacheFOP (e.g. v2.5).  That will address issues such as this related to the old rendering engine.  It may not be suitable for local thick client (e.g. WPF, WinForms), but it will be great for web and server applications....

https://github.com/cajuncoding/ApacheFOP.Serverless

And this project has a branch that has initial support for it providing a nice example of usage in C# MVC...

**Comment by cajuncoding** [comment] 2020-07-18 07:00
Since the issue is related to old implementation of FOP in the FO.Net library, I'm going to close this as that isn't part of the application I will support for updates.  

Instead, see the above comment about using a server-less implementation of Apache FOP (latest version) in an Azure Function as an alternative to interoperate C# projects via micro-service in an Azure Function!

Repo is here: https://github.com/cajuncoding/ApacheFOP.Serverless

**Closed as completed by cajuncoding** 2020-07-18 07:00 UTC
Labels: dependencies
